import type { ToggleAbility } from "@/components/site/AbilityToggle";

export type StatBarRow = { label: string; value: number; hint: string };

export type HeroSpotlight = {
  heroId: string;
  heroSubtitle: string;
  playstyle: string;
  atAGlance: StatBarRow[];
  abilities: ToggleAbility[];
};

const SPOTLIGHTS: Record<string, HeroSpotlight> = {
  voidmancer: {
    heroId: "voidmancer",
    heroSubtitle: "Control the space. Force the choice. Win the ritual peak.",
    playstyle: "ZONE → PULL → RITUAL",
    atAGlance: [
      { label: "Zone control", value: 5, hint: "Area denial" },
      { label: "Pick potential", value: 4, hint: "Forced movement" },
      { label: "Teamfight impact", value: 5, hint: "Ritual peak" },
      { label: "Survivability", value: 2, hint: "Positioning matters" },
      { label: "Skill ceiling", value: 5, hint: "Setup + timing" },
    ],
    abilities: [
      {
        id: "void-sigil",
        slot: "Q",
        name: "Void Sigil",
        type: "Core",
        cooldown: "10s",
        summary: "Place a rune that slows, marks, and claims space for your team.",
        tags: ["Zone", "Control"],
      },
      {
        id: "gravity-shear",
        slot: "E",
        name: "Gravity Shear",
        type: "Utility",
        cooldown: "18s",
        summary: "Pull or shove a small cluster to break formations or peel an engage.",
        tags: ["Displacement", "Peel"],
      },
      {
        id: "abyssal-convergence",
        slot: "R",
        name: "Abyssal Convergence",
        type: "Ultimate",
        cooldown: "90s",
        summary: "Drop a dramatic ritual zone that turns the fight into a yes/no decision.",
        tags: ["Ultimate", "Ritual"],
      },
      {
        id: "rift-step",
        slot: "1",
        name: "Rift Step",
        type: "Mobility",
        cooldown: "16s",
        summary: "Short blink to reposition, dodge telegraphs, or take an angle for the pull.",
        tags: ["Mobility", "Reposition"],
      },
      {
        id: "null-shield",
        slot: "2",
        name: "Null Shield",
        type: "Defensive",
        cooldown: "28s",
        summary: "Brief damage reduction that rewards correct timing during counter-burst.",
        tags: ["Defensive", "Timing"],
      },
      {
        id: "void-mark",
        slot: "3",
        name: "Void Mark",
        type: "Utility",
        cooldown: "22s",
        summary: "Mark a target for a short window—your kit hits harder when the mark is active.",
        tags: ["Debuff", "Window"],
      },
    ],
  },

  warlord: {
    heroId: "warlord",
    heroSubtitle: "Frontline fighter. Rally windows. Big, readable engages.",
    playstyle: "COMMIT → ANCHOR → RALLY",
    atAGlance: [
      { label: "Burst window", value: 5, hint: "Rally peaks" },
      { label: "Cleave / AoE", value: 4, hint: "Frontline sweeps" },
      { label: "Survivability", value: 4, hint: "Stand and call" },
      { label: "Mobility", value: 3, hint: "One commit tool" },
      { label: "Group value", value: 5, hint: "Buff + control" },
    ],
    abilities: [
      {
        id: "shield-break",
        slot: "Q",
        name: "Shield Break",
        type: "Core",
        cooldown: "8s",
        summary: "Heavy strike that cracks a target and opens a kill window.",
        tags: ["Single-target", "Window"],
      },
      {
        id: "command-banner",
        slot: "E",
        name: "Command Banner",
        type: "Utility",
        cooldown: "20s",
        summary: "Plant a banner that anchors the fight and favors allies in its space.",
        tags: ["Zone", "Objective"],
      },
      {
        id: "rally-cry",
        slot: "R",
        name: "Rally Cry",
        type: "Ultimate",
        cooldown: "90s",
        summary: "Short rally window that spikes your team’s tempo to win the fight now.",
        tags: ["Ultimate", "Tempo"],
      },
      {
        id: "charge",
        slot: "1",
        name: "Charge",
        type: "Mobility",
        cooldown: "14s",
        summary: "Committed gap-closer to start the engage or punish positioning.",
        tags: ["Mobility", "Engage"],
      },
      {
        id: "iron-guard",
        slot: "2",
        name: "Iron Guard",
        type: "Defensive",
        cooldown: "30s",
        summary: "Short defensive to hold space and survive counter-burst.",
        tags: ["Defensive", "Hold"],
      },
      {
        id: "battle-shout",
        slot: "3",
        name: "Battle Shout",
        type: "Utility",
        cooldown: "24s",
        summary: "Short-range shout that rallies allies and disrupts nearby enemies.",
        tags: ["Support", "Peel"],
      },
    ],
  },

  architect: {
    heroId: "architect",
    heroSubtitle: "Prep faster. Recover cleaner. Make every run hit harder.",
    playstyle: "PREP → FORTIFY → SURGE",
    atAGlance: [
      { label: "Utility value", value: 5, hint: "Team support" },
      { label: "Defense leverage", value: 4, hint: "Hold windows" },
      { label: "Resource tempo", value: 5, hint: "Craft throughput" },
      { label: "Mobility", value: 2, hint: "Not a duelist" },
      { label: "Fight impact", value: 3, hint: "Windows matter" },
    ],
    abilities: [
      {
        id: "rapid-build",
        slot: "Q",
        name: "Rapid Build",
        type: "Core",
        cooldown: "12s",
        summary: "Fast placement + quick repair burst to stabilize a hold or reset after damage.",
        tags: ["Repair", "Tempo"],
      },
      {
        id: "fortify",
        slot: "E",
        name: "Fortify",
        type: "Utility",
        cooldown: "22s",
        summary: "Temporarily reinforce a key structure or objective point during pressure.",
        tags: ["Defense", "Objective"],
      },
      {
        id: "overcharge-turrets",
        slot: "R",
        name: "Overcharge Turrets",
        type: "Ultimate",
        cooldown: "100s",
        summary: "Short defensive spike window that punishes pushes and buys time to rally.",
        tags: ["Ultimate", "Hold"],
      },
      {
        id: "deploy-cover",
        slot: "1",
        name: "Deploy Cover",
        type: "Utility",
        cooldown: "18s",
        summary: "Drop quick cover to break line-of-sight and protect a revive or loot grab.",
        tags: ["Cover", "Support"],
      },
      {
        id: "salvage",
        slot: "2",
        name: "Salvage",
        type: "Utility",
        cooldown: "28s",
        summary: "Convert nearby scrap into a short buff window (craft speed or repair efficiency).",
        tags: ["Economy", "Buff"],
      },
      {
        id: "shock-net",
        slot: "3",
        name: "Shock Net",
        type: "Control",
        cooldown: "24s",
        summary: "Throw a short snare to stop a diver or lock a doorway during a defend.",
        tags: ["Control", "Peel"],
      },
    ],
  },

  hunter: {
    heroId: "hunter",
    heroSubtitle: "Scout. Pick. Escape with the loot.",
    playstyle: "TRACK → AMBUSH → EXTRACT",
    atAGlance: [
      { label: "Mobility", value: 5, hint: "Chase/escape" },
      { label: "Pick potential", value: 5, hint: "Ambush windows" },
      { label: "Sustain", value: 2, hint: "Don’t brawl" },
      { label: "Information", value: 5, hint: "Tracks + pings" },
      { label: "Teamfight", value: 3, hint: "Skirmish first" },
    ],
    abilities: [
      {
        id: "mark-prey",
        slot: "Q",
        name: "Mark Prey",
        type: "Core",
        cooldown: "12s",
        summary: "Mark a target to reveal trails and turn picks into guaranteed chases.",
        tags: ["Intel", "Pick"],
      },
      {
        id: "smoke-dash",
        slot: "E",
        name: "Smoke Dash",
        type: "Mobility",
        cooldown: "14s",
        summary: "Quick dash that breaks line-of-sight and resets the angle.",
        tags: ["Escape", "Reposition"],
      },
      {
        id: "execution-window",
        slot: "R",
        name: "Execution",
        type: "Ultimate",
        cooldown: "85s",
        summary: "A short finisher window that rewards perfect timing and target selection.",
        tags: ["Ultimate", "Finisher"],
      },
      {
        id: "trapline",
        slot: "1",
        name: "Trapline",
        type: "Control",
        cooldown: "20s",
        summary: "Lay a quick trap to punish pushes or cover a retreat route.",
        tags: ["Control", "Route"],
      },
      {
        id: "grapple",
        slot: "2",
        name: "Grapple",
        type: "Mobility",
        cooldown: "22s",
        summary: "Reposition to high ground or close distance for the pick.",
        tags: ["Mobility", "Angle"],
      },
      {
        id: "flare",
        slot: "3",
        name: "Signal Flare",
        iconName: "Signal Flare (Hunter)",
        type: "Utility",
        cooldown: "30s",
        summary: "Reveal an area briefly—force campers to move or get punished.",
        tags: ["Reveal", "Pressure"],
      },
    ],
  },

  warden: {
    heroId: "warden",
    heroSubtitle: "Hold the line. Protect the objective. Turn pushes into losses.",
    playstyle: "ANCHOR → PEEL → HOLD",
    atAGlance: [
      { label: "Survivability", value: 5, hint: "Tanky" },
      { label: "Peel", value: 5, hint: "Protect allies" },
      { label: "Zone hold", value: 4, hint: "Anchor space" },
      { label: "Damage", value: 2, hint: "Utility-first" },
      { label: "Teamfight", value: 4, hint: "Stabilize chaos" },
    ],
    abilities: [
      {
        id: "bulwark-stance",
        slot: "Q",
        name: "Bulwark Stance",
        type: "Core",
        cooldown: "14s",
        summary: "Enter a stance that reduces damage and makes you harder to move.",
        tags: ["Defensive", "Anchor"],
      },
      {
        id: "ward-field",
        slot: "E",
        name: "Ward Field",
        type: "Utility",
        cooldown: "20s",
        summary: "Protect a small area—ideal for holds, revives, and choke points.",
        tags: ["Zone", "Protection"],
      },
      {
        id: "stand-the-line",
        slot: "R",
        name: "Stand the Line",
        type: "Ultimate",
        cooldown: "100s",
        summary: "A heroic hold window that denies a push and flips tempo.",
        tags: ["Ultimate", "Hold"],
      },
      {
        id: "shield-bash",
        slot: "1",
        name: "Shield Bash",
        type: "Control",
        cooldown: "16s",
        summary: "Stun/interrupt to stop a diver or cancel a key cast.",
        tags: ["Interrupt", "Peel"],
      },
      {
        id: "hook-save",
        slot: "2",
        name: "Hook Save",
        type: "Utility",
        cooldown: "26s",
        summary: "Pull an ally out of danger or reposition them behind the line.",
        tags: ["Save", "Reposition"],
      },
      {
        id: "taunt",
        slot: "3",
        name: "Taunt",
        type: "Utility",
        cooldown: "24s",
        summary: "Force attention in a small radius—buy time for your team to reset.",
        tags: ["Disrupt", "Objective"],
      },
    ],
  },

  mystic: {
    heroId: "mystic",
    heroSubtitle: "Clutch saves. Clean turnarounds. Win the chaos.",
    playstyle: "SAVE → RESET → PUSH",
    atAGlance: [
      { label: "Sustain", value: 5, hint: "Keep squads up" },
      { label: "Utility", value: 5, hint: "Cleanse + buffs" },
      { label: "Burst damage", value: 1, hint: "Not a killer" },
      { label: "Survivability", value: 3, hint: "Positioning" },
      { label: "Teamfight", value: 5, hint: "Turn fights" },
    ],
    abilities: [
      {
        id: "aegis-pulse",
        slot: "Q",
        name: "Aegis Pulse",
        type: "Core",
        cooldown: "10s",
        summary: "Shield nearby allies—timed right, it deletes enemy burst windows.",
        tags: ["Shield", "Timing"],
      },
      {
        id: "cleanse",
        slot: "E",
        name: "Cleanse",
        type: "Utility",
        cooldown: "18s",
        summary: "Remove key debuffs and slow effects to keep rotations alive.",
        tags: ["Cleanse", "Support"],
      },
      {
        id: "sanctuary",
        slot: "R",
        name: "Sanctuary",
        type: "Ultimate",
        cooldown: "95s",
        summary: "Create a short safe zone that enables a turn or a full reset.",
        tags: ["Ultimate", "Zone"],
      },
      {
        id: "blink-heal",
        slot: "1",
        name: "Step of Light",
        type: "Mobility",
        cooldown: "22s",
        summary: "Reposition and tag an ally with a small heal/shield on arrival.",
        tags: ["Mobility", "Support"],
      },
      {
        id: "renew",
        slot: "2",
        name: "Renew",
        type: "Utility",
        cooldown: "24s",
        summary: "Short sustain over time—best used before the damage lands.",
        tags: ["Sustain", "Prep"],
      },
      {
        id: "silence-glyph",
        slot: "3",
        name: "Silence Glyph",
        type: "Control",
        cooldown: "28s",
        summary: "Brief silence field to stop casts and buy a second for the save.",
        tags: ["Control", "Interrupt"],
      },
    ],
  },

  raider: {
    heroId: "raider",
    heroSubtitle: "Make the opening. Break the line. Start the breach.",
    playstyle: "PRESSURE → BREACH → CHAOS",
    atAGlance: [
      { label: "Frontline pressure", value: 5, hint: "Break shields" },
      { label: "AoE threat", value: 4, hint: "Cluster punish" },
      { label: "Survivability", value: 3, hint: "Short windows" },
      { label: "Disruption", value: 5, hint: "Openings" },
      { label: "Mobility", value: 3, hint: "Commit tools" },
    ],
    abilities: [
      {
        id: "breach-charge",
        slot: "Q",
        name: "Breach Charge",
        type: "Core",
        cooldown: "12s",
        summary: "Explosive pressure on clustered foes—forces movement or takes health bars.",
        tags: ["AoE", "Pressure"],
      },
      {
        id: "smoke-screen",
        slot: "E",
        name: "Smoke Screen",
        type: "Utility",
        cooldown: "22s",
        summary: "Break line-of-sight to force resets or cover a push through a choke.",
        tags: ["LoS", "Reset"],
      },
      {
        id: "demolition-rush",
        slot: "R",
        name: "Demolition Rush",
        type: "Ultimate",
        cooldown: "90s",
        summary: "A high-risk breach window: go in, break the line, and dare them to answer.",
        tags: ["Ultimate", "Engage"],
      },
      {
        id: "shatter-slam",
        slot: "1",
        name: "Shatter Slam",
        type: "Control",
        cooldown: "18s",
        summary: "Short knock/interrupt that opens the target for the follow-up.",
        tags: ["Disrupt", "Interrupt"],
      },
      {
        id: "hard-hat",
        slot: "2",
        name: "Hard Hat",
        type: "Defensive",
        cooldown: "30s",
        summary: "Short defensive to survive the counter-burst when you commit.",
        tags: ["Defensive", "Commit"],
      },
      {
        id: "det-pack",
        slot: "3",
        name: "Det Pack",
        type: "Utility",
        cooldown: "26s",
        summary: "Place a timed explosive to deny a doorway or punish a revive.",
        tags: ["Trap", "Zone"],
      },
    ],
  },

  stalker: {
    heroId: "stalker",
    heroSubtitle: "Slip in. Cut the lights. Make logistics a liability.",
    playstyle: "INFILTRATE → SABOTAGE → VANISH",
    atAGlance: [
      { label: "Infiltration", value: 5, hint: "Angles" },
      { label: "Disruption", value: 5, hint: "Sabotage" },
      { label: "Burst", value: 4, hint: "Backline picks" },
      { label: "Survivability", value: 2, hint: "Don’t get caught" },
      { label: "Intel", value: 4, hint: "Routes" },
    ],
    abilities: [
      {
        id: "silent-step",
        slot: "Q",
        name: "Silent Step",
        type: "Core",
        cooldown: "14s",
        summary: "Stealth window for positioning—your fights start where you want them.",
        tags: ["Stealth", "Setup"],
      },
      {
        id: "sapper-kit",
        slot: "E",
        name: "Sapper Kit",
        type: "Utility",
        cooldown: "22s",
        summary: "Disable a defense briefly or sabotage an objective interaction.",
        tags: ["Sabotage", "Objective"],
      },
      {
        id: "blackout",
        slot: "R",
        name: "Blackout",
        type: "Ultimate",
        cooldown: "95s",
        summary: "A short disruption peak that breaks coordination and enables picks.",
        tags: ["Ultimate", "Disruption"],
      },
      {
        id: "smoke-bomb",
        slot: "1",
        name: "Smoke Bomb",
        type: "Utility",
        cooldown: "20s",
        summary: "Hide your exit and force enemies to guess wrong.",
        tags: ["Escape", "LoS"],
      },
      {
        id: "shiv",
        slot: "2",
        name: "Shiv",
        type: "Control",
        cooldown: "18s",
        summary: "Short slow/cripple to secure the pick or stop a chase.",
        tags: ["Slow", "Pick"],
      },
      {
        id: "grappling-line",
        slot: "3",
        name: "Grappling Line",
        type: "Mobility",
        cooldown: "24s",
        summary: "Reposition over walls and terrain—your escape route is vertical.",
        tags: ["Mobility", "Escape"],
      },
    ],
  },

  marshal: {
    heroId: "marshal",
    heroSubtitle: "Turn risky travel into protected movement.",
    playstyle: "RALLY → ESCORT → BREAKTHROUGH",
    atAGlance: [
      { label: "Escort power", value: 5, hint: "Hauls" },
      { label: "Utility", value: 4, hint: "Team buffs" },
      { label: "Survivability", value: 4, hint: "Frontline-lite" },
      { label: "Mobility", value: 3, hint: "Rotations" },
      { label: "Fight impact", value: 4, hint: "Momentum" },
    ],
    abilities: [
      {
        id: "escort-orders",
        slot: "Q",
        name: "Escort Orders",
        type: "Core",
        cooldown: "12s",
        summary: "Buff nearby allies—your squad moves and fights as one unit.",
        tags: ["Buff", "Squad"],
      },
      {
        id: "signal-flare",
        slot: "E",
        name: "Signal Flare",
        iconName: "Signal Flare (Marshal)",
        type: "Utility",
        cooldown: "24s",
        summary: "Call a rally to a marked point—pull teammates into the moment.",
        tags: ["Rally", "Objective"],
      },
      {
        id: "breakthrough",
        slot: "R",
        name: "Breakthrough",
        type: "Ultimate",
        cooldown: "95s",
        summary: "A coordinated push/escape window that forces the fight to move.",
        tags: ["Ultimate", "Momentum"],
      },
      {
        id: "banner-wall",
        slot: "1",
        name: "Banner Wall",
        type: "Utility",
        cooldown: "20s",
        summary: "Temporary cover and protection to survive crossfire during rotations.",
        tags: ["Cover", "Escort"],
      },
      {
        id: "stun-shot",
        slot: "2",
        name: "Stun Shot",
        type: "Control",
        cooldown: "18s",
        summary: "Stop a chaser or cancel a key ability during a retreat or rescue.",
        tags: ["Interrupt", "Peel"],
      },
      {
        id: "rations",
        slot: "3",
        name: "Field Rations",
        type: "Utility",
        cooldown: "30s",
        summary: "Short sustain + stamina boost—keep the convoy moving.",
        tags: ["Sustain", "Travel"],
      },
    ],
  },
};

export function getHeroSpotlight(heroId: string): HeroSpotlight | undefined {
  return SPOTLIGHTS[heroId];
}

